### ISSUE TITLE
Index was outside the bounds of the array When Golum Boss is Defeated.

### ISSUE THREAD

**Issue by Sumenora** [Arrenton/Leveled#26]
The following Error is produced upon Demise.

Silently Caught Exception: Index was outside the bounds of the array.   at Leveled.NPCs.AI.AIHandler.AI(NPC npc, NPCStats modNpc, Mod mod)   at DMD<Terraria.ModLoader.ModCompile+<>c::<ActivateExceptionReporting>b__15_0>(<>c , Object , FirstChanceExceptionEventArgs )
   at TerrariaHooks.TerrariaHooksManager.OnLogSilentException(Action`3 orig, Object self, Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at Hook<Terraria.ModLoader.ModCompile+<>c::<ActivateExceptionReporting>b__15_0>?60584892(<>c , Object , FirstChanceExceptionEventArgs )
   at Leveled.NPCs.AI.AIHandler.AI(NPC npc, NPCStats modNpc, Mod mod)
   at Leveled.NPCs.NPCStats.PreAI(NPC npc)
   at Terraria.ModLoader.NPCLoader.PreAI(NPC npc)
   at Terraria.ModLoader.NPCLoader.NPCAI(NPC npc)
   at Terraria.NPC.UpdateNPC(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

- Consistent 

Leveled 1.0.1

**Comment by Arrenton** [comment]
In single player or multiplayer?

**Comment by Sumenora** [comment]
> 
> 
> In single player or multiplayer?

Both

**Comment by Arrenton** [comment]
Did you summon Golem the normal way, or use something like Cheat Sheet/HERO's?

**Comment by Sumenora** [comment]
> 
> 
> Did you summon Golem the normal way, or use something like Cheat Sheet/HERO's?

Its been summoned the normal way using the "Power Cell" in the Temple, No Cheat Sheet or Heros mod are used to preserve accuracy.

**Comment by webmilio** [comment]
#18 was closed because of unreproducability on our end. Let's hope we can reproduce this one.
